import type {
  Agent, AgentGraph, Client, Lead, Task,
  RevenueSnapshot, RileyContent, AgentLog, DailyBrief, CommandSummary
} from './types'

// ============================================================
// AGENTS
// ============================================================

export const AGENTS: Agent[] = [
  {
    id: 'BIG_HOMIE',
    name: 'BIG HOMIE',
    role: 'Master Orchestrator',
    status: 'active',
    lastActive: 'NOW',
    tasksCompleted: 247,
    tasksTotal: 247,
    currentTask: 'Generating Daily Command Brief',
    color: '#ff6b00',
    glowColor: 'rgba(255,107,0,0.8)',
  },
  {
    id: 'PLUG',
    name: 'PLUG',
    role: 'Partnerships & Opportunities',
    status: 'active',
    lastActive: '2m ago',
    tasksCompleted: 12,
    tasksTotal: 15,
    currentTask: 'Scanning partnership opportunities',
    color: '#8b5cf6',
    glowColor: 'rgba(139,92,246,0.7)',
  },
  {
    id: 'HUNTER',
    name: 'HUNTER',
    role: 'Lead Generation',
    status: 'processing',
    lastActive: '1m ago',
    tasksCompleted: 34,
    tasksTotal: 40,
    currentTask: 'Qualifying 6 new leads from Facebook Ads',
    color: '#00d4ff',
    glowColor: 'rgba(0,212,255,0.7)',
  },
  {
    id: 'CLOSER',
    name: 'CLOSER',
    role: 'Sales',
    status: 'active',
    lastActive: '5m ago',
    tasksCompleted: 8,
    tasksTotal: 12,
    currentTask: 'Following up with Apex Media proposal',
    color: '#ff2200',
    glowColor: 'rgba(255,34,0,0.7)',
  },
  {
    id: 'SAUCE',
    name: 'SAUCE',
    role: 'Creative Strategy',
    status: 'idle',
    lastActive: '22m ago',
    tasksCompleted: 19,
    tasksTotal: 22,
    currentTask: undefined,
    color: '#ffd700',
    glowColor: 'rgba(255,215,0,0.7)',
  },
  {
    id: 'CUTTY',
    name: 'CUTTY',
    role: 'Content & Media',
    status: 'processing',
    lastActive: '3m ago',
    tasksCompleted: 28,
    tasksTotal: 35,
    currentTask: 'Editing Riley Stone Week 24 Reel',
    color: '#00ff88',
    glowColor: 'rgba(0,255,136,0.7)',
  },
  {
    id: 'HUSTLE',
    name: 'HUSTLE',
    role: 'Advertising & Growth',
    status: 'active',
    lastActive: '8m ago',
    tasksCompleted: 15,
    tasksTotal: 18,
    currentTask: 'Optimizing Facebook Ad campaigns',
    color: '#ff6b00',
    glowColor: 'rgba(255,107,0,0.6)',
  },
  {
    id: 'LOOKOUT',
    name: 'LOOKOUT',
    role: 'Market Intelligence',
    status: 'active',
    lastActive: '4m ago',
    tasksCompleted: 41,
    tasksTotal: 45,
    currentTask: 'Monitoring competitor content performance',
    color: '#00d4ff',
    glowColor: 'rgba(0,212,255,0.6)',
  },
  {
    id: 'GEAR',
    name: 'GEAR',
    role: 'Development & Automation',
    status: 'processing',
    lastActive: '1m ago',
    tasksCompleted: 22,
    tasksTotal: 30,
    currentTask: 'Building Command Center WebSocket bridge',
    color: '#8b5cf6',
    glowColor: 'rgba(139,92,246,0.6)',
  },
  {
    id: 'OG',
    name: 'OG',
    role: 'Operations & Compliance',
    status: 'idle',
    lastActive: '1h ago',
    tasksCompleted: 33,
    tasksTotal: 35,
    currentTask: undefined,
    color: '#ffd700',
    glowColor: 'rgba(255,215,0,0.6)',
  },
  {
    id: 'BAGMAN',
    name: 'BAGMAN',
    role: 'Finance',
    status: 'idle',
    lastActive: '2h ago',
    tasksCompleted: 11,
    tasksTotal: 12,
    currentTask: undefined,
    color: '#00ff88',
    glowColor: 'rgba(0,255,136,0.6)',
  },
  {
    id: 'RILEY',
    name: 'RILEY',
    role: 'Riley Stone Influencer Division',
    status: 'active',
    lastActive: '15m ago',
    tasksCompleted: 47,
    tasksTotal: 52,
    currentTask: 'Scheduling Week 25 content calendar',
    color: '#ff2200',
    glowColor: 'rgba(255,34,0,0.6)',
  },
]

// ============================================================
// AGENT NETWORK GRAPH
// ============================================================

export const AGENT_GRAPH: AgentGraph = {
  nodes: [
    { id: 'BIG_HOMIE', name: 'BIG HOMIE', role: 'Master Orchestrator', status: 'active', color: '#ff6b00', val: 20, fx: 0, fy: 0 },
    { id: 'PLUG',      name: 'PLUG',      role: 'Partnerships',        status: 'active',     color: '#8b5cf6', val: 8 },
    { id: 'HUNTER',   name: 'HUNTER',    role: 'Lead Gen',            status: 'processing',  color: '#00d4ff', val: 8 },
    { id: 'CLOSER',   name: 'CLOSER',    role: 'Sales',               status: 'active',     color: '#ff2200', val: 8 },
    { id: 'SAUCE',    name: 'SAUCE',     role: 'Creative',            status: 'idle',       color: '#ffd700', val: 8 },
    { id: 'CUTTY',    name: 'CUTTY',     role: 'Content',             status: 'processing', color: '#00ff88', val: 8 },
    { id: 'HUSTLE',   name: 'HUSTLE',    role: 'Advertising',         status: 'active',     color: '#ff6b00', val: 8 },
    { id: 'LOOKOUT',  name: 'LOOKOUT',   role: 'Intel',               status: 'active',     color: '#00d4ff', val: 8 },
    { id: 'GEAR',     name: 'GEAR',      role: 'Dev & Auto',          status: 'processing', color: '#8b5cf6', val: 8 },
    { id: 'OG',       name: 'OG',        role: 'Operations',          status: 'idle',       color: '#ffd700', val: 8 },
    { id: 'BAGMAN',   name: 'BAGMAN',    role: 'Finance',             status: 'idle',       color: '#00ff88', val: 8 },
    { id: 'RILEY',    name: 'RILEY',     role: 'Influencer',          status: 'active',     color: '#ff2200', val: 10 },
  ],
  links: [
    { source: 'BIG_HOMIE', target: 'PLUG',    value: 3 },
    { source: 'BIG_HOMIE', target: 'HUNTER',  value: 3 },
    { source: 'BIG_HOMIE', target: 'CLOSER',  value: 3 },
    { source: 'BIG_HOMIE', target: 'SAUCE',   value: 3 },
    { source: 'BIG_HOMIE', target: 'CUTTY',   value: 3 },
    { source: 'BIG_HOMIE', target: 'HUSTLE',  value: 3 },
    { source: 'BIG_HOMIE', target: 'LOOKOUT', value: 3 },
    { source: 'BIG_HOMIE', target: 'GEAR',    value: 3 },
    { source: 'BIG_HOMIE', target: 'OG',      value: 3 },
    { source: 'BIG_HOMIE', target: 'BAGMAN',  value: 3 },
    { source: 'BIG_HOMIE', target: 'RILEY',   value: 4 },
    { source: 'HUNTER',    target: 'CLOSER',  value: 2 },
    { source: 'CLOSER',    target: 'BAGMAN',  value: 2 },
    { source: 'SAUCE',     target: 'CUTTY',   value: 2 },
    { source: 'CUTTY',     target: 'RILEY',   value: 2 },
    { source: 'HUSTLE',    target: 'LOOKOUT', value: 2 },
    { source: 'PLUG',      target: 'OG',      value: 1 },
    { source: 'GEAR',      target: 'OG',      value: 1 },
    { source: 'HUSTLE',    target: 'HUNTER',  value: 1 },
  ],
}

// ============================================================
// CLIENTS
// ============================================================

export const CLIENTS: Client[] = [
  {
    id: 'c1',
    name: 'Marcus Thompson',
    company: 'Apex Media Group',
    status: 'active',
    monthlyValue: 3500,
    nextAction: 'Send Q3 content report',
    assignedAgent: 'CLOSER',
    lastContact: '2 days ago',
  },
  {
    id: 'c2',
    name: 'Tanya Rivera',
    company: 'Midwest Realty Co',
    status: 'at_risk',
    monthlyValue: 2200,
    nextAction: 'Schedule check-in call ASAP',
    assignedAgent: 'OG',
    lastContact: '12 days ago',
  },
  {
    id: 'c3',
    name: 'Derek Fontaine',
    company: 'Northstar Fitness',
    status: 'active',
    monthlyValue: 1800,
    nextAction: 'Deliver brand refresh mockups',
    assignedAgent: 'SAUCE',
    lastContact: '1 day ago',
  },
  {
    id: 'c4',
    name: 'Priya Kapoor',
    company: 'Central MN Dental',
    status: 'active',
    monthlyValue: 2800,
    nextAction: 'Review Facebook Ads performance',
    assignedAgent: 'HUSTLE',
    lastContact: '3 days ago',
  },
  {
    id: 'c5',
    name: 'Jason Holt',
    company: 'Holt Construction',
    status: 'prospect',
    monthlyValue: 0,
    nextAction: 'Send proposal by Friday',
    assignedAgent: 'CLOSER',
    lastContact: '1 day ago',
  },
]

// ============================================================
// LEADS / SALES PIPELINE
// ============================================================

export const LEADS: Lead[] = [
  {
    id: 'l1',
    name: 'Sarah Mills',
    company: 'Mills Law Group',
    source: 'Referral',
    stage: 'proposal',
    estimatedValue: 4500,
    assignedAgent: 'CLOSER',
    lastActivity: '1 day ago',
    nextStep: 'Follow up on $4,500/mo proposal',
  },
  {
    id: 'l2',
    name: 'Kevin Bauer',
    company: 'Bauer Brewing',
    source: 'Facebook Ads',
    stage: 'qualified',
    estimatedValue: 2800,
    assignedAgent: 'HUNTER',
    lastActivity: '2 days ago',
    nextStep: 'Schedule discovery call',
  },
  {
    id: 'l3',
    name: 'Angela Torres',
    company: 'Torres Aesthetics',
    source: 'Instagram DM',
    stage: 'negotiation',
    estimatedValue: 3200,
    assignedAgent: 'CLOSER',
    lastActivity: '3h ago',
    nextStep: 'Negotiate onboarding timeline',
  },
  {
    id: 'l4',
    name: 'Mike Carlson',
    company: 'Carlson Auto',
    source: 'Cold Outreach',
    stage: 'contacted',
    estimatedValue: 1500,
    assignedAgent: 'HUNTER',
    lastActivity: '5 days ago',
    nextStep: 'Send intro video + case studies',
  },
  {
    id: 'l5',
    name: 'Diane Park',
    company: 'Park Photography',
    source: 'GHL Campaign',
    stage: 'new',
    estimatedValue: 1200,
    assignedAgent: 'HUNTER',
    lastActivity: '1h ago',
    nextStep: 'Initial qualification call',
  },
  {
    id: 'l6',
    name: 'Tom Fletcher',
    company: 'Fletcher Financial',
    source: 'LinkedIn',
    stage: 'won',
    estimatedValue: 5000,
    assignedAgent: 'CLOSER',
    lastActivity: 'Yesterday',
    nextStep: 'Onboarding kickoff',
  },
]

// ============================================================
// TASKS / PRODUCTION QUEUE
// ============================================================

export const TASKS: Task[] = [
  {
    id: 't1',
    title: 'Riley Stone Week 24 Reel — Final Edit',
    agent: 'CUTTY',
    priority: 'critical',
    status: 'in_progress',
    dueDate: 'Today 5PM',
    category: 'content',
  },
  {
    id: 't2',
    title: 'Apex Media Q3 Content Report',
    agent: 'CLOSER',
    priority: 'high',
    status: 'pending',
    dueDate: 'Tomorrow',
    category: 'client',
  },
  {
    id: 't3',
    title: 'Fletcher Financial Onboarding Deck',
    agent: 'SAUCE',
    priority: 'high',
    status: 'in_progress',
    dueDate: 'Jun 9',
    category: 'sales',
  },
  {
    id: 't4',
    title: 'Central MN Dental Facebook Ads Audit',
    agent: 'HUSTLE',
    priority: 'medium',
    status: 'in_progress',
    dueDate: 'Jun 8',
    category: 'marketing',
  },
  {
    id: 't5',
    title: 'Command Center WebSocket Integration',
    agent: 'GEAR',
    priority: 'high',
    status: 'in_progress',
    dueDate: 'Jun 10',
    category: 'development',
  },
  {
    id: 't6',
    title: 'Midwest Realty Client Check-In',
    agent: 'OG',
    priority: 'critical',
    status: 'pending',
    dueDate: 'Today',
    category: 'client',
  },
  {
    id: 't7',
    title: 'Week 25 Riley Content Calendar',
    agent: 'RILEY',
    priority: 'medium',
    status: 'review',
    dueDate: 'Jun 9',
    category: 'content',
  },
  {
    id: 't8',
    title: 'Holt Construction Proposal',
    agent: 'CLOSER',
    priority: 'high',
    status: 'pending',
    dueDate: 'Jun 7',
    category: 'sales',
  },
  {
    id: 't9',
    title: 'Monthly Revenue Report — BAGMAN',
    agent: 'BAGMAN',
    priority: 'medium',
    status: 'completed',
    dueDate: 'Jun 6',
    category: 'ops',
    completedAt: 'Today 9:00 AM',
  },
  {
    id: 't10',
    title: 'Partnership Deck for TBR 247 x Local Media',
    agent: 'PLUG',
    priority: 'medium',
    status: 'pending',
    dueDate: 'Jun 12',
    category: 'sales',
  },
]

// ============================================================
// REVENUE
// ============================================================

export const REVENUE_SNAPSHOT: RevenueSnapshot = {
  currentMRR: 14800,
  mrrTarget: 20000,
  mrrGrowth: 18.4,
  totalClients: 8,
  avgDealSize: 2600,
  pipeline: 17200,
  history: [
    { month: 'Jan', mrr: 7200,  newRevenue: 1200, target: 10000, churn: 0 },
    { month: 'Feb', mrr: 8400,  newRevenue: 1800, target: 11000, churn: 600 },
    { month: 'Mar', mrr: 9800,  newRevenue: 2200, target: 12000, churn: 800 },
    { month: 'Apr', mrr: 11200, newRevenue: 2800, target: 13000, churn: 1400 },
    { month: 'May', mrr: 12500, newRevenue: 3200, target: 15000, churn: 1900 },
    { month: 'Jun', mrr: 14800, newRevenue: 5000, target: 20000, churn: 2700 },
  ],
}

// ============================================================
// RILEY STONE CONTENT
// ============================================================

export const RILEY_CONTENT: RileyContent[] = [
  {
    id: 'rc1',
    title: '"Morning Mindset" — Week 24 Reel',
    platform: 'Instagram',
    type: 'Reel',
    status: 'editing',
    scheduledDate: 'Jun 7, 9AM',
    notes: 'Hook: "Your mindset at 7AM = your results at 7PM"',
  },
  {
    id: 'rc2',
    title: 'Behind-the-Scenes: Content Shoot Day',
    platform: 'TikTok',
    status: 'review',
    type: 'Video',
    scheduledDate: 'Jun 8, 6PM',
  },
  {
    id: 'rc3',
    title: 'Top 5 Tools I Use to Run My Brand',
    platform: 'YouTube',
    type: 'Video',
    status: 'scripting',
    scheduledDate: 'Jun 12',
    notes: 'Long-form, 8-12 min. CUTTY owns this.',
  },
  {
    id: 'rc4',
    title: 'Daily Story Series — June Week 3',
    platform: 'Instagram',
    type: 'Story',
    status: 'scheduled',
    scheduledDate: 'Jun 9-13',
  },
  {
    id: 'rc5',
    title: '"Discipline Over Motivation" Quote Post',
    platform: 'Instagram',
    type: 'Post',
    status: 'scheduled',
    scheduledDate: 'Jun 7, 12PM',
    views: 0,
    engagement: 0,
  },
  {
    id: 'rc6',
    title: 'Client Success Story Thread',
    platform: 'Twitter/X',
    type: 'Thread',
    status: 'idea',
    notes: 'Feature Apex Media results. Needs SAUCE approval.',
  },
  {
    id: 'rc7',
    title: '"Why I Left Corporate" — Week 23 Reel',
    platform: 'TikTok',
    type: 'Reel',
    status: 'published',
    publishedDate: 'Jun 1',
    views: 14800,
    engagement: 8.4,
  },
]

// ============================================================
// AGENT LOGS
// ============================================================

export const AGENT_LOGS: AgentLog[] = [
  {
    id: 'log1',
    timestamp: '2026-06-06T09:47:00Z',
    agent: 'SYSTEM',
    action: 'COMMAND CENTER ONLINE',
    details: 'League 247 Command Center initialized. All systems nominal.',
    type: 'system',
  },
  {
    id: 'log2',
    timestamp: '2026-06-06T09:47:03Z',
    agent: 'BIG_HOMIE',
    action: 'AGENT ONLINE',
    details: "What's up Rob — BIG HOMIE is online. Generating Daily Command Brief...",
    type: 'activation',
  },
  {
    id: 'log3',
    timestamp: '2026-06-06T09:47:15Z',
    agent: 'BIG_HOMIE',
    action: 'BRIEF GENERATED',
    details: 'Daily Command Brief for June 6, 2026 complete. 10 sections. 3 critical priorities.',
    type: 'brief',
  },
  {
    id: 'log4',
    timestamp: '2026-06-06T09:48:02Z',
    agent: 'HUNTER',
    action: 'LEADS SCANNED',
    details: 'Pulled 6 new leads from GHL pipeline. 3 qualified, 2 nurture, 1 hot.',
    type: 'ghl',
  },
  {
    id: 'log5',
    timestamp: '2026-06-06T09:49:30Z',
    agent: 'GEAR',
    action: 'BUILD IN PROGRESS',
    details: 'WebSocket bridge active. Real-time event stream: 12 msg/min.',
    type: 'system',
  },
  {
    id: 'log6',
    timestamp: '2026-06-06T09:51:00Z',
    agent: 'CUTTY',
    action: 'TASK STARTED',
    details: 'Riley Stone Week 24 Reel — entering final edit phase. ETA: 4h.',
    type: 'task_complete',
  },
  {
    id: 'log7',
    timestamp: '2026-06-06T09:52:45Z',
    agent: 'CLOSER',
    action: 'FOLLOW-UP SENT',
    details: 'Apex Media proposal follow-up sent via GHL. Tagged: PRIORITY.',
    type: 'ghl',
  },
  {
    id: 'log8',
    timestamp: '2026-06-06T09:55:12Z',
    agent: 'OG',
    action: 'ALERT',
    details: '⚠ Midwest Realty — 12 days without contact. Flag for immediate attention.',
    type: 'alert',
  },
  {
    id: 'log9',
    timestamp: '2026-06-06T10:01:00Z',
    agent: 'HUSTLE',
    action: 'CAMPAIGN OPTIMIZED',
    details: 'Central MN Dental Facebook Ads: CPL reduced 23% after audience refinement.',
    type: 'task_complete',
  },
  {
    id: 'log10',
    timestamp: '2026-06-06T10:05:00Z',
    agent: 'BAGMAN',
    action: 'REPORT FILED',
    details: 'May 2026 Revenue Report submitted. MRR: $12,500. Up 22% vs April.',
    type: 'task_complete',
  },
]

// ============================================================
// DAILY BRIEF
// ============================================================

export const DAILY_BRIEF: DailyBrief = {
  generatedAt: '2026-06-06T09:47:15Z',
  greeting: "What's up Rob — BIG HOMIE is online. Here's your Command Brief for June 6.",
  priorities: [
    'Close Holt Construction — proposal due by end of day Friday',
    'Call Midwest Realty (Tanya Rivera) — 12 days no contact, at risk',
    'Approve Riley Stone Week 24 Reel before 5PM for tomorrow schedule',
  ],
  clientAttention: [
    { client: 'Midwest Realty (Tanya)', issue: '12 days no contact — at-risk flag', action: 'Schedule call today' },
    { client: 'Apex Media (Marcus)', issue: 'Q3 report overdue by 2 days', action: 'CLOSER sends by EOD' },
    { client: 'Central MN Dental (Priya)', issue: 'Ads audit needed before Fri meeting', action: 'HUSTLE delivers audit by Thu' },
  ],
  salesOpportunities: [
    { lead: 'Torres Aesthetics — Angela', value: 3200, nextStep: 'Negotiate timeline, close this week' },
    { lead: 'Mills Law Group — Sarah', value: 4500, nextStep: 'Proposal follow-up call today' },
    { lead: 'Fletcher Financial — Tom', value: 5000, nextStep: 'Start onboarding ASAP — already won' },
    { lead: 'Holt Construction — Jason', value: 0, nextStep: 'Send proposal by Friday EOD' },
  ],
  rileyTasks: [
    'Approve Week 24 "Morning Mindset" Reel — due today, posts Jun 7',
    'CUTTY: Final edit on Week 24 Reel by 5PM',
    'RILEY: Lock in Week 25 content calendar by Monday',
    'SAUCE: Review YouTube script outline — "Top 5 Tools"',
  ],
  productionQueue: [
    'Riley Stone Week 24 Reel (CUTTY — IN PROGRESS)',
    'Fletcher Financial Onboarding Deck (SAUCE — IN PROGRESS)',
    'Apex Media Q3 Content Report (CLOSER — PENDING)',
    'Holt Construction Proposal (CLOSER — PENDING)',
    'Partnership Deck TBR 247 (PLUG — PENDING)',
  ],
  ghlFollowUps: [
    'Angela Torres — Negotiation stage, last touch 3h ago',
    'Sarah Mills — Proposal sent, awaiting response',
    'Kevin Bauer — Qualified, book discovery call',
    'Mike Carlson — Send case studies (5 days cold)',
    'Midwest Realty — Mark as at-risk in GHL, schedule task',
  ],
  teamAssignments: [
    { agent: 'CLOSER', task: 'Apex Media report + Holt proposal + Torres close' },
    { agent: 'CUTTY', task: 'Riley Week 24 final edit' },
    { agent: 'HUSTLE', task: 'Central MN Dental ads audit' },
    { agent: 'OG', task: 'Midwest Realty client recovery call' },
    { agent: 'SAUCE', task: 'Fletcher onboarding deck' },
    { agent: 'RILEY', task: 'Week 25 calendar lock' },
  ],
  revenueOpportunities: [
    'Torres Aesthetics close = +$3,200/mo MRR',
    'Mills Law Group = +$4,500/mo MRR if proposal converts',
    'Holt Construction = est. +$2,000-3,500/mo',
    'Fletcher Financial already won = +$5,000/mo starting Jun 15',
  ],
  robShouldDoFirst: [
    '1. Call Tanya Rivera (Midwest Realty) — retention priority',
    '2. Approve Riley Stone Reel — unlock CUTTY\'s delivery pipeline',
    '3. Review Torres Aesthetics negotiation notes with CLOSER',
    '4. Confirm Holt Construction proposal is locked for Friday',
  ],
  endOfDayChecklist: [
    '☐ Riley Reel approved and scheduled',
    '☐ Apex Media report sent',
    '☐ Midwest Realty contact made',
    '☐ Holt proposal finalized',
    '☐ GHL pipeline updated',
    '☐ BAGMAN runs EOD revenue check',
    '☐ BIG HOMIE end-of-day debrief logged',
  ],
}

// ============================================================
// COMMAND SUMMARY
// ============================================================

export const COMMAND_SUMMARY: CommandSummary = {
  timestamp: '2026-06-06T10:05:00Z',
  activeAgents: 7,
  totalAgents: 12,
  tasksInProgress: 5,
  tasksCompletedToday: 3,
  leadsInPipeline: 5,
  newLeadsToday: 2,
  currentMRR: 14800,
  rileyPostsThisWeek: 3,
  systemStatus: 'nominal',
}
